services:
  - type: web
    name: vila-reserva
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
